# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: CopyFiles@2
  inputs:
    Contents: |
      deploy/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Docker@2
  inputs:
    containerRegistry: 'xorCube Azure Container Registry'
    repository: 'hobbystacks/registrar.api'
    command: 'buildAndPush'
    Dockerfile: 'src/Services/Registrar/Registrar.Api/Dockerfile'
    buildContext: 
    tags: 'latest'

- task: Docker@2
  inputs:
    containerRegistry: 'xorCube Azure Container Registry'
    repository: 'hobbystacks/web.spa'
    command: 'buildAndPush'
    Dockerfile: 'src/WebApps/HeroAcademy.WebSpa/Dockerfile'
    buildContext: 
    tags: 'latest'
