version: '3.4'

services:
  postgresql.data:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - heroacademy

  postgresql.adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgresql.data
    depends_on:
      - postgresql.data
    restart: unless-stopped
    networks:
      - heroacademy

  registrar.api:
    image: ${REGISTRY:-xorcube.azurecr.io}/heroacademy/registrar.api:${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Registrar/Registrar.Api/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgresql.data
    restart: unless-stopped
    networks:
      - heroacademy

  web.spa:
    image: ${REGISTRY:-xorcube.azurecr.io}/heroacademy/web.spa:${TAG:-dev}
    build:
      context: .
      dockerfile: src/WebApps/HeroAcademy.WebSpa/Dockerfile.develop
    depends_on:
      - registrar.api
    restart: unless-stopped
    networks:
      - heroacademy

networks:
  heroacademy: