version: '3.4'

services:
  postgresql.data:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - heroacademy

  postgresql.adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgresql.data
    depends_on:
      - postgresql.data
    restart: unless-stopped
    networks:
      - heroacademy

  nginx:
    image: nginx:alpine
    ports:
      - 8000:8000
      - 9000:9000
      - 8001:8001
      - 9001:9001
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/nginx:/etc/nginx/conf.d
    depends_on:
      - registrar.api
      - web.spa
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - heroacademy

  registrar.api:
    image: ${REGISTRY:-xorcube.azurecr.io}/heroacademy/registrar.api:${TAG:-dev}
    build:
      context: .
      dockerfile: src/Services/Registrar/Registrar.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgresql.data
    restart: unless-stopped
    networks:
      - heroacademy

  web.spa:
    image: ${REGISTRY:-xorcube.azurecr.io}/heroacademy/web.spa:${TAG:-dev}
    build:
      context: .
      dockerfile: src/WebApps/HeroAcademy.WebSpa/Dockerfile.develop
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - registrar.api
    restart: unless-stopped
    networks:
      - heroacademy

networks:
  heroacademy: